<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SmtOrderManager.Application\SmtOrderManager.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SmtOrderManager.Infrastructure.Tests" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
