<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SmtOrderManager.Domain\SmtOrderManager.Domain.csproj" />
    <ProjectReference Include="..\..\src\SmtOrderManager.Application\SmtOrderManager.Application.csproj" />
    <ProjectReference Include="..\..\src\SmtOrderManager.Infrastructure\SmtOrderManager.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\SmtOrderManager.Application.Tests\Contracts\order-download.v1.json"
          Link="Contracts\order-download.v1.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>