<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SmtOrderManager.Domain\SmtOrderManager.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SmtOrderManager.Application.Tests" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
